<?php
session_start();
$db=new mysqli('localhost','root','','KrazePlanetLabs_DB');
if($db->connect_error)die('<h3 style="padding:32px;font-family:sans-serif;color:#c00">DB error: '.htmlspecialchars($db->connect_error).'</h3>');
$db->query("CREATE TABLE IF NOT EXISTS lab1402_users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100)NOT NULL,email VARCHAR(255)NOT NULL UNIQUE,password VARCHAR(255)NOT NULL,role VARCHAR(100)DEFAULT'Operator',avatar VARCHAR(4)DEFAULT'U',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
$chk=$db->query("SELECT id FROM lab1402_users WHERE email='david.ops@cloudsms.io'");
if($chk&&$chk->num_rows===0){$seeds=[['David Chen','david.ops@cloudsms.io','david@123','SMS Operator','DC'],['Nina Ross','nina.r@cloudsms.io','nina@123','Route Manager','NR'],['Kevin Lee','kevin.l@cloudsms.io','kevin@123','API Admin','KL']];$st=$db->prepare("INSERT INTO lab1402_users(name,email,password,role,avatar)VALUES(?,?,?,?,?)");foreach($seeds as $s){$h=password_hash($s[2],PASSWORD_BCRYPT);$st->bind_param('sssss',$s[0],$s[1],$h,$s[3],$s[4]);$st->execute();}$st->close();}
function esc($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$action=$_GET['action']??'';$error='';
if($action==='logout'){session_destroy();header('Location:'.$_SERVER['PHP_SELF']);exit;}
$me=null;if(!empty($_SESSION['lab1402_uid'])){$st=$db->prepare("SELECT*FROM lab1402_users WHERE id=?");$st->bind_param('i',$_SESSION['lab1402_uid']);$st->execute();$me=$st->get_result()->fetch_assoc();$st->close();}
if($action==='register'&&$_SERVER['REQUEST_METHOD']==='POST'){$n=trim($_POST['reg_name']??'');$e=trim($_POST['reg_email']??'');$p=$_POST['reg_password']??'';if($n&&$e&&$p){$h=password_hash($p,PASSWORD_BCRYPT);$av=strtoupper(substr($n,0,1).(strpos($n,' ')!==false?substr($n,strpos($n,' ')+1,1):substr($n,1,1)));$st=$db->prepare("INSERT INTO lab1402_users(name,email,password,avatar)VALUES(?,?,?,?)");$st->bind_param('ssss',$n,$e,$h,$av);if($st->execute()){$_SESSION['lab1402_uid']=$db->insert_id;header('Location:'.$_SERVER['PHP_SELF']);exit;}$error='Email already registered.';$st->close();}else $error='All fields required.';}
if($action!=='register'&&!$me&&$_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['email'])){$e=trim($_POST['email']);$p=$_POST['password']??'';if($e&&$p){$st=$db->prepare("SELECT*FROM lab1402_users WHERE email=?");$st->bind_param('s',$e);$st->execute();$u=$st->get_result()->fetch_assoc();$st->close();if($u&&password_verify($p,$u['password'])){$_SESSION['lab1402_uid']=$u['id'];header('Location:'.$_SERVER['PHP_SELF']);exit;}$error='Invalid email or password.';}}
// XML API
if($_SERVER['REQUEST_METHOD']==='POST'&&$me){$raw=file_get_contents('php://input');$ct=$_SERVER['CONTENT_TYPE']??'';if(stripos($ct,'xml')!==false||stripos(trim($raw),'<?xml')===0||stripos(trim($raw),'<operation')===0){header('Content-Type: application/xml');if(function_exists('libxml_disable_entity_loader'))@libxml_disable_entity_loader(false);libxml_use_internal_errors(true);$dom=new DOMDocument();$ok=@$dom->loadXML($raw,LIBXML_NOENT|LIBXML_DTDLOAD);libxml_clear_errors();if($ok){$nodes=$dom->getElementsByTagName('operatorId');$opId=($nodes->length>0)?$nodes->item(0)->textContent:'';if(!empty($opId)&&!ctype_digit(trim($opId))){$esc=esc($opId);echo"<?xml version=\"1.0\"?>\n<operation type=\"deliver\">\n  <error code=\"1010\" message=\"Unable to convert [{$esc}] to an integer for [operatorId]\"/>\n</operation>";}else echo"<?xml version=\"1.0\"?>\n<operation type=\"deliver\">\n  <response status=\"0\" message=\"Message queued. Delivery receipt pending.\"/>\n</operation>";}else{http_response_code(400);echo"<?xml version=\"1.0\"?>\n<operation type=\"deliver\">\n  <error code=\"9000\" message=\"XML Parse Error\"/>\n</operation>";}if(function_exists('libxml_disable_entity_loader'))@libxml_disable_entity_loader(true);exit;}}
$loggedIn=(bool)$me;$ta=[];if(!$loggedIn){$r=$db->query("SELECT name,email FROM lab1402_users ORDER BY id LIMIT 3");while($row=$r->fetch_assoc())$ta[]=$row;}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>CloudSMS<?=$loggedIn?' — Console':($action==='register'?' — Register':' — Sign In')?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#0f172a;color:#e2e8f0;min-height:100vh}.aw{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.ac{background:#1e293b;border:1px solid #334155;border-radius:12px;width:100%;max-width:420px;padding:40px 36px 32px}.alogo{width:56px;height:56px;border-radius:14px;background:linear-gradient(135deg,#0ea5e9,#0284c7);display:flex;align-items:center;justify-content:center;margin:0 auto 20px}.alogo svg{width:28px;height:28px;stroke:#fff;fill:none;stroke-width:2}.att{text-align:center;font-size:1.25rem;font-weight:600;margin-bottom:4px}.asu{text-align:center;font-size:.85rem;color:#64748b;margin-bottom:28px}.fl{font-size:.78rem;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;display:block}.fi{width:100%;padding:10px 14px;border:1px solid #334155;border-radius:8px;font-size:.88rem;color:#e2e8f0;background:#0f172a}.fi:focus{outline:none;border-color:#0ea5e9;box-shadow:0 0 0 3px rgba(14,165,233,.15)}.fi::placeholder{color:#475569}.bauth{width:100%;padding:11px;border:none;border-radius:8px;font-weight:600;font-size:.9rem;cursor:pointer;background:#0ea5e9;color:#fff;margin-top:8px}.bauth:hover{background:#0284c7}.ae{background:rgba(239,68,68,.1);border:1px solid #7f1d1d;border-radius:6px;padding:8px 12px;font-size:.82rem;color:#fca5a5;margin-bottom:16px;text-align:center}.tbx{background:#0f172a;border:1px solid #334155;border-radius:8px;margin-top:20px;overflow:hidden}.tbh{padding:8px 14px;font-size:.72rem;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #1e293b;display:flex;align-items:center;gap:6px}.tbr{padding:7px 14px;display:flex;align-items:center;font-size:.8rem;border-bottom:1px solid #1e293b;cursor:pointer}.tbr:last-child{border-bottom:none}.tbr:hover{background:rgba(14,165,233,.08)}.tbe{color:#94a3b8;flex:1}.tbp{color:#64748b;font-family:monospace;font-size:.78rem}.afo{text-align:center;margin-top:20px;font-size:.85rem;color:#64748b}.afo a{color:#0ea5e9;text-decoration:none;font-weight:500}
.nb{background:#020617;border-bottom:1px solid #1e293b;display:flex;align-items:center;height:48px;padding:0 20px}.nb-brand{font-weight:700;font-size:.95rem;color:#38bdf8;display:flex;align-items:center;gap:8px;text-decoration:none}.nb-brand svg{width:22px;height:22px}.nb-nav{display:flex;margin-left:32px;height:100%}.nb-nav a{color:#64748b;text-decoration:none;padding:0 14px;display:flex;align-items:center;font-size:.82rem;font-weight:500;height:100%;border-bottom:2px solid transparent}.nb-nav a:hover{color:#94a3b8}.nb-nav a.act{color:#e2e8f0;border-bottom-color:#38bdf8}.nb-r{margin-left:auto;display:flex;align-items:center;gap:12px;font-size:.8rem;color:#64748b}.nb-r .av{width:30px;height:30px;border-radius:50%;background:linear-gradient(135deg,#0ea5e9,#0284c7);display:flex;align-items:center;justify-content:center;font-size:.68rem;font-weight:700;color:#fff}.nb-r .ui{text-align:right;line-height:1.3}.nb-r .un{font-size:.8rem;color:#e2e8f0;font-weight:500}.nb-r .ur{font-size:.68rem;color:#475569}.blo{color:#64748b;text-decoration:none;font-size:.76rem;padding:3px 8px;border:1px solid #334155;border-radius:5px}.blo:hover{color:#f87171;border-color:#7f1d1d}.dot{width:7px;height:7px;border-radius:50%;background:#22c55e;display:inline-block}
.pw{max-width:1100px;margin:0 auto;padding:24px 16px}.ptt{font-size:1.2rem;font-weight:600;margin-bottom:4px}.psu{font-size:.82rem;color:#64748b;margin-bottom:20px}.sr{display:flex;gap:12px;margin-bottom:16px}.sc{flex:1;background:#1e293b;border:1px solid #334155;border-radius:6px;padding:12px;text-align:center}.snum{font-size:1.3rem;font-weight:700;color:#38bdf8}.slbl{font-size:.7rem;color:#64748b;text-transform:uppercase;letter-spacing:.05em;margin-top:2px}.pn{background:#1e293b;border:1px solid #334155;border-radius:8px;overflow:hidden}.pnh{padding:10px 16px;background:#0f172a;border-bottom:1px solid #334155;font-size:.8rem;font-weight:600;color:#94a3b8;display:flex;align-items:center;gap:8px}.pnb{padding:16px}.dfl{font-size:.82rem;color:#64748b;font-weight:500;margin-bottom:6px;display:block}.dfi{width:100%;padding:9px 14px;border:1px solid #334155;border-radius:6px;font-size:.88rem;color:#e2e8f0;background:#0f172a}.dfi:focus{outline:none;border-color:#38bdf8;box-shadow:0 0 0 3px rgba(56,189,248,.15)}.dfi::placeholder{color:#475569}.dfs{width:100%;padding:9px 14px;border:1px solid #334155;border-radius:6px;font-size:.88rem;color:#e2e8f0;background:#0f172a;appearance:auto}.bsnd{background:#0ea5e9;color:#fff;border:none;padding:9px 24px;border-radius:6px;font-weight:600;font-size:.85rem;cursor:pointer;display:inline-flex;align-items:center;gap:6px}.bsnd:hover{background:#0284c7}.bsnd:disabled{opacity:.5;cursor:not-allowed}.rbox{background:#0f172a;border:1px solid #334155;border-radius:6px;padding:12px 14px;font-family:'Consolas',monospace;font-size:.8rem;white-space:pre-wrap;word-break:break-all;min-height:80px}.rbox.ok{color:#4ade80}.rbox.er{color:#fb923c}.dbox{background:#0f172a;border:1px solid #334155;border-radius:6px;padding:14px;font-size:.78rem;color:#64748b;line-height:1.65;margin-bottom:12px}.dbox strong{color:#94a3b8}.dbox code{background:#1e293b;padding:1px 5px;border-radius:3px;color:#38bdf8;font-size:.76rem}.dep{font-family:monospace;background:#020617;color:#67e8f9;padding:6px 10px;border-radius:4px;font-size:.76rem;margin:6px 0;display:block;border:1px solid #1e293b}.lrow{padding:6px 0;border-bottom:1px solid #1e293b;font-size:.78rem;display:flex;justify-content:space-between}.lrow:last-child{border-bottom:none}.ltm{color:#475569;font-family:monospace;font-size:.72rem}.spin{display:inline-block;width:16px;height:16px;border:2px solid #fff;border-top-color:transparent;border-radius:50%;animation:sp .6s linear infinite}@keyframes sp{to{transform:rotate(360deg)}}#ra{display:none}.ft{text-align:center;padding:20px;color:#334155;font-size:.72rem;margin-top:40px}</style>
</head><body>
<?php if(!$loggedIn):?>
<?php if($action==='register'):?>
<div class="aw"><div class="ac"><div class="alogo"><svg viewBox="0 0 24 24"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/></svg></div><div class="att">Create Account</div><div class="asu">Join CloudSMS Gateway</div><?php if($error):?><div class="ae"><?=esc($error)?></div><?php endif;?><form method="POST"><div class="mb-3"><label class="fl">Full Name</label><input type="text" name="reg_name" class="fi" placeholder="John Doe" required></div><div class="mb-3"><label class="fl">Email</label><input type="email" name="reg_email" class="fi" placeholder="you@cloudsms.io" required></div><div class="mb-3"><label class="fl">Password</label><input type="password" name="reg_password" class="fi" placeholder="Password" required></div><button type="submit" class="bauth">Create Account</button></form><div class="afo">Have an account? <a href="?">Sign in</a></div></div></div>
<?php else:?>
<div class="aw"><div class="ac"><div class="alogo"><svg viewBox="0 0 24 24"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/></svg></div><div class="att">Sign in to CloudSMS</div><div class="asu">Welcome back</div><?php if($error):?><div class="ae"><i class="bi bi-exclamation-circle me-1"></i><?=esc($error)?></div><?php endif;?><form method="POST"><div class="mb-3"><label class="fl">Email</label><input type="email" name="email" class="fi" placeholder="you@cloudsms.io" required></div><div class="mb-3"><label class="fl">Password</label><input type="password" name="password" class="fi" placeholder="Password" required></div><button type="submit" class="bauth">Sign In</button></form><div class="tbx"><div class="tbh"><i class="bi bi-shield-lock"></i> Test Accounts</div><?php foreach($ta as $t):$pw=explode('.',explode('@',$t['email'])[0])[0].'@123';?><div class="tbr" onclick="document.querySelector('[name=email]').value='<?=esc($t['email'])?>';document.querySelector('[name=password]').value='<?=esc($pw)?>'"><span class="tbe"><?=esc($t['email'])?></span><span class="tbp"><?=esc($pw)?></span></div><?php endforeach;?></div><div class="afo">New here? <a href="?action=register">Create account</a></div></div></div>
<?php endif;?>
<?php else:?>
<div class="nb"><a href="#" class="nb-brand"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/></svg>CloudSMS</a><div class="nb-nav"><a href="#">Dashboard</a><a href="#" class="act">Send Message</a><a href="#">Logs</a><a href="#">Routes</a><a href="#">API Keys</a></div><div class="nb-r"><div class="ui"><div class="un"><?=esc($me['name'])?></div><div class="ur"><?=esc($me['role'])?></div></div><div class="av"><?=esc($me['avatar'])?></div><a href="?action=logout" class="blo"><i class="bi bi-box-arrow-right"></i></a></div></div>
<div class="pw"><div class="ptt"><i class="bi bi-send me-2"></i>Send SMS</div><div class="psu">Compose and send SMS through the gateway.</div>
<div class="sr"><div class="sc"><div class="snum">12,847</div><div class="slbl">Sent Today</div></div><div class="sc"><div class="snum">99.2%</div><div class="slbl">Delivery</div></div><div class="sc"><div class="snum">23ms</div><div class="slbl">Latency</div></div><div class="sc"><div class="snum">3</div><div class="slbl">Routes</div></div></div>
<div class="row g-4"><div class="col-lg-8"><div class="pn mb-4"><div class="pnh"><i class="bi bi-chat-dots"></i> Compose</div><div class="pnb"><form id="sf" onsubmit="return send(event)"><div class="row g-3 mb-3"><div class="col-md-6"><label class="dfl">Carrier ID</label><select id="cid" class="dfs"><option value="40404">40404 — US Mobile</option><option value="44444">44444 — UK Vodafone</option><option value="86100">86100 — CN Unicom</option></select></div><div class="col-md-6"><label class="dfl">Short Code</label><input type="text" id="sc2" class="dfi" value="40404"></div></div><div class="mb-3"><label class="dfl">Recipient</label><input type="text" id="rcp" class="dfi" placeholder="+1555012345" value="+1555012345"></div><div class="mb-3"><label class="dfl">Message</label><textarea id="msg" class="dfi" rows="3" style="resize:vertical">Your verification code is 847291</textarea></div><button type="submit" class="bsnd" id="btn"><i class="bi bi-send"></i> Send</button></form></div></div>
<div id="ra" class="pn"><div class="pnh"><i class="bi bi-arrow-return-left"></i> Response <span id="sb" style="margin-left:auto"></span></div><div class="pnb"><div id="rbx" class="rbox ok"></div></div></div></div>
<div class="col-lg-4"><div class="pn mb-4"><div class="pnh"><i class="bi bi-book"></i> API Info</div><div class="pnb"><div class="dbox"><strong>Protocol</strong><span class="dep">SXMP v1.0 (XML/HTTP)</span><code>&lt;operatorId&gt;</code> must be integer.</div><div class="dbox"><strong>Errors</strong><ul style="margin:6px 0 0;padding-left:16px;font-size:.76rem"><li><code>1010</code> — Invalid type</li><li><code>9000</code> — Parse error</li></ul></div></div></div>
<div class="pn"><div class="pnh"><i class="bi bi-clock-history"></i> Recent</div><div class="pnb"><div class="lrow"><span style="color:#4ade80">✓ +1555098712</span><span class="ltm">23:31</span></div><div class="lrow"><span style="color:#4ade80">✓ +4478556123</span><span class="ltm">23:30</span></div><div class="lrow"><span style="color:#fb923c">✗ +8613800001</span><span class="ltm">23:29</span></div></div></div></div></div></div>
<div class="ft">CloudSMS Gateway © 2026</div>
<?php endif;?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<?php if($loggedIn):?><script>
function send(e){if(e)e.preventDefault();var c=document.getElementById('cid').value,s=document.getElementById('sc2').value,r=document.getElementById('rcp').value,m=document.getElementById('msg').value,b=document.getElementById('btn');var xml='<?xml version="1.0" encoding="ISO-8859-1"?>\n<operation type="deliver">\n  <account username="sxmp_user" password="key"/>\n  <deliverRequest referenceId="REF'+Date.now()+'">\n    <operatorId>'+c+'</operatorId>\n    <sourceAddress type="network">'+s+'</sourceAddress>\n    <destinationAddress type="international">'+r+'</destinationAddress>\n    <text encoding="ISO-8859-1">'+m+'</text>\n  </deliverRequest>\n</operation>';b.disabled=true;b.innerHTML='<span class="spin"></span> Sending...';fetch(window.location.pathname,{method:'POST',headers:{'Content-Type':'text/xml'},body:xml}).then(function(r){return r.text()}).then(function(t){b.disabled=false;b.innerHTML='<i class="bi bi-send"></i> Send';document.getElementById('ra').style.display='block';var bx=document.getElementById('rbx');bx.textContent=t;bx.className='rbox '+(t.indexOf('error')!==-1?'er':'ok');document.getElementById('sb').innerHTML=t.indexOf('error')!==-1?'<span style="color:#f87171;font-size:.76rem">Error</span>':'<span style="color:#4ade80;font-size:.76rem">200 OK</span>'}).catch(function(){b.disabled=false;b.innerHTML='<i class="bi bi-send"></i> Send'});return false;}
</script><?php endif;?>
</body></html>