<?php
session_start();
$db=new mysqli('localhost','root','','KrazePlanetLabs_DB');
if($db->connect_error)die('<h3 style="padding:32px;font-family:sans-serif;color:#c00">DB: '.htmlspecialchars($db->connect_error).'</h3>');
$db->query("CREATE TABLE IF NOT EXISTS lab1403_users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100)NOT NULL,email VARCHAR(255)NOT NULL UNIQUE,password VARCHAR(255)NOT NULL,crew VARCHAR(100)DEFAULT'Ghost Squad',avatar VARCHAR(4)DEFAULT'U',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
$chk=$db->query("SELECT id FROM lab1403_users WHERE email='shadow@crewforge.gg'");
if($chk&&$chk->num_rows===0){$seeds=[['ShadowHunter','shadow@crewforge.gg','shadow@123','Ghost Squad','SH'],['NovaStrike','nova@crewforge.gg','nova@123','Nova Elite','NS'],['ViperX','viper@crewforge.gg','viper@123','Viper Protocol','VX']];$st=$db->prepare("INSERT INTO lab1403_users(name,email,password,crew,avatar)VALUES(?,?,?,?,?)");foreach($seeds as $s){$h=password_hash($s[2],PASSWORD_BCRYPT);$st->bind_param('sssss',$s[0],$s[1],$h,$s[3],$s[4]);$st->execute();}$st->close();}
function esc($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$action=$_GET['action']??'';$error='';
if($action==='logout'){session_destroy();header('Location:'.$_SERVER['PHP_SELF']);exit;}
$me=null;if(!empty($_SESSION['lab1403_uid'])){$st=$db->prepare("SELECT*FROM lab1403_users WHERE id=?");$st->bind_param('i',$_SESSION['lab1403_uid']);$st->execute();$me=$st->get_result()->fetch_assoc();$st->close();}
if($action==='register'&&$_SERVER['REQUEST_METHOD']==='POST'){$n=trim($_POST['reg_name']??'');$e=trim($_POST['reg_email']??'');$p=$_POST['reg_password']??'';if($n&&$e&&$p){$h=password_hash($p,PASSWORD_BCRYPT);$av=strtoupper(substr($n,0,2));$st=$db->prepare("INSERT INTO lab1403_users(name,email,password,avatar)VALUES(?,?,?,?)");$st->bind_param('ssss',$n,$e,$h,$av);if($st->execute()){$_SESSION['lab1403_uid']=$db->insert_id;header('Location:'.$_SERVER['PHP_SELF']);exit;}$error='Username taken.';$st->close();}else $error='All fields required.';}
if($action!=='register'&&!$me&&$_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['email'])){$e=trim($_POST['email']);$p=$_POST['password']??'';if($e&&$p){$st=$db->prepare("SELECT*FROM lab1403_users WHERE email=?");$st->bind_param('s',$e);$st->execute();$u=$st->get_result()->fetch_assoc();$st->close();if($u&&password_verify($p,$u['password'])){$_SESSION['lab1403_uid']=$u['id'];header('Location:'.$_SERVER['PHP_SELF']);exit;}$error='Invalid credentials.';}}
// SVG XML API
if($_SERVER['REQUEST_METHOD']==='POST'&&$me){$raw=file_get_contents('php://input');$ct=$_SERVER['CONTENT_TYPE']??'';if(stripos($ct,'xml')!==false||stripos($ct,'svg')!==false||stripos(trim($raw),'<?xml')===0||stripos(trim($raw),'<svg')===0){header('Content-Type: application/json');if(function_exists('libxml_disable_entity_loader'))@libxml_disable_entity_loader(false);libxml_use_internal_errors(true);$dom=new DOMDocument();$ok=@$dom->loadXML($raw,LIBXML_NOENT|LIBXML_DTDLOAD);libxml_clear_errors();if($ok){$txt='';foreach(['text','tspan']as$tag){$nodes=$dom->getElementsByTagName($tag);for($i=0;$i<$nodes->length;$i++)$txt.=$nodes->item($i)->textContent;}echo json_encode(['status'=>'ok','text_content'=>$txt,'rendered'=>true]);}else{http_response_code(400);echo json_encode(['status'=>'error','message'=>'Invalid SVG']);}if(function_exists('libxml_disable_entity_loader'))@libxml_disable_entity_loader(true);exit;}}
$loggedIn=(bool)$me;$ta=[];if(!$loggedIn){$r=$db->query("SELECT name,email FROM lab1403_users ORDER BY id LIMIT 3");while($row=$r->fetch_assoc())$ta[]=$row;}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>CrewForge<?=$loggedIn?' — Emblem Editor':($action==='register'?' — Register':' — Sign In')?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#111827;color:#e5e7eb;min-height:100vh}.aw{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.ac{background:#1f2937;border:1px solid #374151;border-radius:12px;width:100%;max-width:420px;padding:40px 36px 32px}.alogo{width:56px;height:56px;border-radius:14px;background:linear-gradient(135deg,#f59e0b,#d97706);display:flex;align-items:center;justify-content:center;margin:0 auto 20px;font-size:1.4rem;color:#000;font-weight:800}.att{text-align:center;font-size:1.25rem;font-weight:600;margin-bottom:4px}.asu{text-align:center;font-size:.85rem;color:#6b7280;margin-bottom:28px}.fl{font-size:.78rem;font-weight:600;color:#9ca3af;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;display:block}.fi{width:100%;padding:10px 14px;border:1px solid #374151;border-radius:8px;font-size:.88rem;color:#e5e7eb;background:#111827}.fi:focus{outline:none;border-color:#f59e0b;box-shadow:0 0 0 3px rgba(245,158,11,.15)}.fi::placeholder{color:#4b5563}.bauth{width:100%;padding:11px;border:none;border-radius:8px;font-weight:700;font-size:.9rem;cursor:pointer;background:#f59e0b;color:#000;margin-top:8px}.bauth:hover{background:#d97706}.ae{background:rgba(239,68,68,.1);border:1px solid #7f1d1d;border-radius:6px;padding:8px 12px;font-size:.82rem;color:#fca5a5;margin-bottom:16px;text-align:center}.tbx{background:#111827;border:1px solid #374151;border-radius:8px;margin-top:20px;overflow:hidden}.tbh{padding:8px 14px;font-size:.72rem;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #1f2937;display:flex;align-items:center;gap:6px}.tbr{padding:7px 14px;display:flex;align-items:center;font-size:.8rem;border-bottom:1px solid #1f2937;cursor:pointer}.tbr:last-child{border-bottom:none}.tbr:hover{background:rgba(245,158,11,.08)}.tbe{color:#9ca3af;flex:1}.tbp{color:#6b7280;font-family:monospace;font-size:.78rem}.afo{text-align:center;margin-top:20px;font-size:.85rem;color:#6b7280}.afo a{color:#f59e0b;text-decoration:none;font-weight:500}
.nb{background:#030712;border-bottom:1px solid #1f2937;display:flex;align-items:center;height:50px;padding:0 20px}.nb-brand{font-weight:800;font-size:1rem;color:#f59e0b;display:flex;align-items:center;gap:8px;text-decoration:none}.nb-nav{display:flex;margin-left:28px;height:100%}.nb-nav a{color:#6b7280;text-decoration:none;padding:0 14px;display:flex;align-items:center;font-size:.82rem;font-weight:500;height:100%;border-bottom:2px solid transparent}.nb-nav a:hover{color:#d1d5db}.nb-nav a.act{color:#f9fafb;border-bottom-color:#f59e0b}.nb-r{margin-left:auto;display:flex;align-items:center;gap:14px;font-size:.8rem;color:#6b7280}.nb-r .av{width:30px;height:30px;border-radius:50%;background:linear-gradient(135deg,#f59e0b,#d97706);display:flex;align-items:center;justify-content:center;font-size:.7rem;font-weight:700;color:#000}.nb-r .un{font-size:.82rem;color:#e5e7eb;font-weight:500}.blo{color:#6b7280;text-decoration:none;font-size:.76rem;padding:3px 8px;border:1px solid #374151;border-radius:5px}.blo:hover{color:#f87171;border-color:#7f1d1d}
.pw{max-width:1100px;margin:0 auto;padding:24px 16px}.ptt{font-size:1.2rem;font-weight:600;margin-bottom:4px}.psu{font-size:.82rem;color:#6b7280;margin-bottom:20px}.pn{background:#1f2937;border:1px solid #374151;border-radius:8px;overflow:hidden}.pnh{padding:10px 16px;background:#111827;border-bottom:1px solid #374151;font-size:.8rem;font-weight:600;color:#9ca3af;display:flex;align-items:center;gap:8px}.pnb{padding:16px}.uz{border:2px dashed #374151;border-radius:12px;padding:40px 20px;text-align:center;cursor:pointer;transition:border-color .2s}.uz:hover{border-color:#f59e0b}.uz i{font-size:2.5rem;color:#4b5563;margin-bottom:12px}.uz p{font-size:.88rem;color:#9ca3af;margin-bottom:4px}.uz small{font-size:.78rem;color:#4b5563}.bup{background:#f59e0b;color:#000;border:none;padding:8px 20px;border-radius:6px;font-weight:700;font-size:.82rem;cursor:pointer;display:inline-flex;align-items:center;gap:6px}.bup:hover{background:#d97706}.bup:disabled{opacity:.5;cursor:not-allowed}.pv{background:#030712;border:2px solid #374151;border-radius:12px;width:200px;height:200px;display:flex;align-items:center;justify-content:center;overflow:hidden}.pv.lk{border-color:#ef4444;box-shadow:0 0 20px rgba(239,68,68,.2)}.pvt{color:#fff;font-size:.65rem;padding:6px;word-break:break-all;text-align:center;font-family:monospace;max-height:190px;overflow:auto}.exf{background:#0f172a;border:1px solid #374151;border-radius:6px;padding:12px;font-family:monospace;font-size:.78rem;color:#fca5a5;white-space:pre-wrap;word-break:break-all;max-height:280px;overflow-y:auto}.ftag{background:#111827;border:1px solid #374151;border-radius:6px;padding:6px 12px;font-size:.82rem;color:#9ca3af;display:none;align-items:center;gap:8px;margin-bottom:12px}.ftag i{color:#f59e0b}.crew-card{background:#111827;border:1px solid #374151;border-radius:8px;padding:12px;display:flex;align-items:center;gap:12px;margin-bottom:8px}.ce{width:40px;height:40px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:.7rem;color:#000}.cn{font-weight:600;font-size:.85rem}.cm{font-size:.72rem;color:#6b7280}.spin{display:inline-block;width:16px;height:16px;border:2px solid #000;border-top-color:transparent;border-radius:50%;animation:sp .6s linear infinite}@keyframes sp{to{transform:rotate(360deg)}}#ra{display:none}.ft{text-align:center;padding:20px;color:#374151;font-size:.72rem;margin-top:40px}</style>
</head><body>
<?php if(!$loggedIn):?>
<?php if($action==='register'):?>
<div class="aw"><div class="ac"><div class="alogo">⚔</div><div class="att">Join CrewForge</div><div class="asu">Create your player account</div><?php if($error):?><div class="ae"><?=esc($error)?></div><?php endif;?><form method="POST"><div class="mb-3"><label class="fl">Gamertag</label><input type="text" name="reg_name" class="fi" placeholder="xShadowHunter" required></div><div class="mb-3"><label class="fl">Email</label><input type="email" name="reg_email" class="fi" placeholder="you@crewforge.gg" required></div><div class="mb-3"><label class="fl">Password</label><input type="password" name="reg_password" class="fi" placeholder="Password" required></div><button type="submit" class="bauth">Create Account</button></form><div class="afo">Already a member? <a href="?">Sign in</a></div></div></div>
<?php else:?>
<div class="aw"><div class="ac"><div class="alogo">⚔</div><div class="att">Sign in to CrewForge</div><div class="asu">Welcome back, warrior</div><?php if($error):?><div class="ae"><i class="bi bi-exclamation-circle me-1"></i><?=esc($error)?></div><?php endif;?><form method="POST"><div class="mb-3"><label class="fl">Email</label><input type="email" name="email" class="fi" placeholder="you@crewforge.gg" required></div><div class="mb-3"><label class="fl">Password</label><input type="password" name="password" class="fi" placeholder="Password" required></div><button type="submit" class="bauth">Sign In</button></form><div class="tbx"><div class="tbh"><i class="bi bi-shield-lock"></i> Test Accounts</div><?php foreach($ta as $t):$pw=explode('@',$t['email'])[0].'@123';?><div class="tbr" onclick="document.querySelector('[name=email]').value='<?=esc($t['email'])?>';document.querySelector('[name=password]').value='<?=esc($pw)?>'"><span class="tbe"><?=esc($t['email'])?></span><span class="tbp"><?=esc($pw)?></span></div><?php endforeach;?></div><div class="afo">New player? <a href="?action=register">Create account</a></div></div></div>
<?php endif;?>
<?php else:?>
<div class="nb"><a href="#" class="nb-brand"><i class="bi bi-shield-fill"></i> CrewForge</a><div class="nb-nav"><a href="#">Home</a><a href="#" class="act">Emblem Editor</a><a href="#">My Crews</a><a href="#">Leaderboards</a></div><div class="nb-r"><span class="un"><?=esc($me['name'])?></span><div class="av"><?=esc($me['avatar'])?></div><a href="?action=logout" class="blo"><i class="bi bi-box-arrow-right"></i></a></div></div>
<div class="pw"><div class="ptt"><i class="bi bi-palette me-2"></i>Crew Emblem Editor</div><div class="psu">Upload an SVG file to create your crew's emblem badge.</div>
<div class="row g-4"><div class="col-lg-8"><div class="pn mb-4"><div class="pnh"><i class="bi bi-upload"></i> Upload Emblem <span style="margin-left:auto;font-size:.72rem;color:#4b5563">SVG · 200x200</span></div><div class="pnb"><div class="uz" id="dz" onclick="document.getElementById('finp').click()"><i class="bi bi-cloud-arrow-up d-block"></i><p><strong>Drag & drop</strong> your SVG file</p><small>or click to browse</small></div><input type="file" id="finp" accept=".svg,image/svg+xml" style="display:none" onchange="hf(this.files[0])"><div class="ftag" id="ftag"><i class="bi bi-file-earmark-code"></i><span id="fname"></span><span style="margin-left:auto;font-size:.72rem" id="fsize"></span></div><div class="mt-3"><button class="bup" id="ubtn" disabled onclick="upload()"><i class="bi bi-upload"></i> Upload</button></div></div></div>
<div id="ra" class="pn"><div class="pnh"><i class="bi bi-image"></i> Preview</div><div class="pnb"><div class="d-flex gap-4 align-items-start flex-wrap"><div><div class="pv" id="pvb"><span style="color:#4b5563;font-size:.8rem">No emblem</span></div><p style="font-size:.7rem;color:#4b5563;margin-top:6px;text-align:center">200x200 PNG</p></div><div id="exa" style="flex:1;min-width:200px;display:none"><p style="font-size:.82rem;color:#9ca3af;margin-bottom:8px">Rendered text:</p><div class="exf" id="exb"></div></div></div></div></div></div>
<div class="col-lg-4"><div class="pn mb-4"><div class="pnh"><i class="bi bi-info-circle"></i> Guidelines</div><div class="pnb" style="font-size:.8rem;color:#9ca3af;line-height:1.7"><ul style="padding-left:16px;margin:0"><li>SVG format only</li><li>200x200 canvas</li><li>Server converts to PNG</li><li>External refs supported</li></ul></div></div>
<div class="pn"><div class="pnh"><i class="bi bi-people-fill"></i> Top Crews</div><div class="pnb"><div class="crew-card"><div class="ce" style="background:#ef4444">DK</div><div><div class="cn">Death Knights</div><div class="cm">2,341 members</div></div></div><div class="crew-card"><div class="ce" style="background:#3b82f6">NV</div><div><div class="cn">Nova Elite</div><div class="cm">1,876 members</div></div></div><div class="crew-card" style="margin-bottom:0"><div class="ce" style="background:#f59e0b">GS</div><div><div class="cn">Ghost Squad</div><div class="cm">984 members</div></div></div></div></div></div></div></div>
<div class="ft">CrewForge © 2026</div>
<?php endif;?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<?php if($loggedIn):?><script>
var svgD=null;var dz=document.getElementById('dz');dz.addEventListener('dragover',function(e){e.preventDefault();dz.style.borderColor='#f59e0b'});dz.addEventListener('dragleave',function(){dz.style.borderColor='#374151'});dz.addEventListener('drop',function(e){e.preventDefault();dz.style.borderColor='#374151';if(e.dataTransfer.files.length)hf(e.dataTransfer.files[0])});
function hf(f){if(!f)return;document.getElementById('ftag').style.display='flex';document.getElementById('fname').textContent=f.name;document.getElementById('fsize').textContent=(f.size/1024).toFixed(1)+' KB';document.getElementById('ubtn').disabled=false;var r=new FileReader();r.onload=function(e){svgD=e.target.result};r.readAsText(f)}
function upload(){if(!svgD)return;var b=document.getElementById('ubtn');b.disabled=true;b.innerHTML='<span class="spin"></span> Uploading...';fetch(window.location.pathname,{method:'POST',headers:{'Content-Type':'image/svg+xml'},body:svgD}).then(function(r){return r.json()}).then(function(d){b.disabled=false;b.innerHTML='<i class="bi bi-upload"></i> Upload';document.getElementById('ra').style.display='block';var pv=document.getElementById('pvb');if(d.text_content){pv.innerHTML='<div class="pvt">'+esc(d.text_content)+'</div>';if(d.text_content.length>20&&(d.text_content.indexOf(':')!==-1||d.text_content.indexOf('/')!==-1)){pv.classList.add('lk');document.getElementById('exa').style.display='block';document.getElementById('exb').textContent=d.text_content}}else pv.innerHTML='<span style="color:#4b5563;font-size:.8rem">No text</span>'}).catch(function(){b.disabled=false;b.innerHTML='<i class="bi bi-upload"></i> Upload'})}
function esc(s){var d=document.createElement('div');d.appendChild(document.createTextNode(s));return d.innerHTML}
</script><?php endif;?>
</body></html>