<?php
session_start();
$db=new mysqli('localhost','root','','KrazePlanetLabs_DB');
if($db->connect_error)die('<h3 style="padding:32px;font-family:sans-serif;color:#c00">DB: '.htmlspecialchars($db->connect_error).'</h3>');
$db->query("CREATE TABLE IF NOT EXISTS lab1405_users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100)NOT NULL,email VARCHAR(255)NOT NULL UNIQUE,password VARCHAR(255)NOT NULL,role VARCHAR(100)DEFAULT'Applicant',avatar VARCHAR(4)DEFAULT'U',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
$chk=$db->query("SELECT id FROM lab1405_users WHERE email='jane.s@talentbridge.io'");
if($chk&&$chk->num_rows===0){$seeds=[['Jane Smith','jane.s@talentbridge.io','jane@123','Applicant','JS'],['Mike Chen','mike.c@talentbridge.io','mike@123','Applicant','MC'],['Priya Raj','priya.r@talentbridge.io','priya@123','Applicant','PR']];$st=$db->prepare("INSERT INTO lab1405_users(name,email,password,role,avatar)VALUES(?,?,?,?,?)");foreach($seeds as $s){$h=password_hash($s[2],PASSWORD_BCRYPT);$st->bind_param('sssss',$s[0],$s[1],$h,$s[3],$s[4]);$st->execute();}$st->close();}
function esc($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$action=$_GET['action']??'';$error='';
if($action==='logout'){session_destroy();header('Location:'.$_SERVER['PHP_SELF']);exit;}
$me=null;if(!empty($_SESSION['lab1405_uid'])){$st=$db->prepare("SELECT*FROM lab1405_users WHERE id=?");$st->bind_param('i',$_SESSION['lab1405_uid']);$st->execute();$me=$st->get_result()->fetch_assoc();$st->close();}
if($action==='register'&&$_SERVER['REQUEST_METHOD']==='POST'){$n=trim($_POST['reg_name']??'');$e=trim($_POST['reg_email']??'');$p=$_POST['reg_password']??'';if($n&&$e&&$p){$h=password_hash($p,PASSWORD_BCRYPT);$av=strtoupper(substr($n,0,1).(strpos($n,' ')!==false?substr($n,strpos($n,' ')+1,1):substr($n,1,1)));$st=$db->prepare("INSERT INTO lab1405_users(name,email,password,avatar)VALUES(?,?,?,?)");$st->bind_param('ssss',$n,$e,$h,$av);if($st->execute()){$_SESSION['lab1405_uid']=$db->insert_id;header('Location:'.$_SERVER['PHP_SELF']);exit;}$error='Email taken.';$st->close();}else $error='All fields required.';}
if($action!=='register'&&!$me&&$_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['email'])){$e=trim($_POST['email']);$p=$_POST['password']??'';if($e&&$p){$st=$db->prepare("SELECT*FROM lab1405_users WHERE email=?");$st->bind_param('s',$e);$st->execute();$u=$st->get_result()->fetch_assoc();$st->close();if($u&&password_verify($p,$u['password'])){$_SESSION['lab1405_uid']=$u['id'];header('Location:'.$_SERVER['PHP_SELF']);exit;}$error='Invalid credentials.';}}
// Resume XML API
if($_SERVER['REQUEST_METHOD']==='POST'&&$me){$raw=file_get_contents('php://input');$ct=$_SERVER['CONTENT_TYPE']??'';if(stripos($ct,'xml')!==false||stripos(trim($raw),'<?xml')===0||stripos(trim($raw),'<resume')===0){header('Content-Type: application/json');if(function_exists('libxml_disable_entity_loader'))@libxml_disable_entity_loader(false);libxml_use_internal_errors(true);$dom=new DOMDocument();$ok=@$dom->loadXML($raw,LIBXML_NOENT|LIBXML_DTDLOAD);libxml_clear_errors();if($ok){$fields=['name'=>'personal/name','email'=>'personal/email','phone'=>'personal/phone','objective'=>'objective','job_title'=>'experience/job/title','company'=>'experience/job/company','degree'=>'education/degree','university'=>'education/university'];$xp=new DOMXPath($dom);$parsed=[];foreach($fields as$k=>$path){$nodes=$xp->query('//'.$path);if($nodes&&$nodes->length>0)$parsed[$k]=$nodes->item(0)->textContent;}echo json_encode(['status'=>'ok','message'=>'Resume parsed','fields'=>$parsed]);}else{http_response_code(400);echo json_encode(['status'=>'error','message'=>'Invalid format']);}if(function_exists('libxml_disable_entity_loader'))@libxml_disable_entity_loader(true);exit;}}
$loggedIn=(bool)$me;$ta=[];if(!$loggedIn){$r=$db->query("SELECT name,email FROM lab1405_users ORDER BY id LIMIT 3");while($row=$r->fetch_assoc())$ta[]=$row;}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>TalentBridge<?=$loggedIn?' — Apply':($action==='register'?' — Register':' — Sign In')?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9fafb;color:#111827;min-height:100vh}.aw{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px;background:#f0fdf4}.ac{background:#fff;border:1px solid #d1fae5;border-radius:12px;width:100%;max-width:420px;padding:40px 36px 32px}.alogo{width:56px;height:56px;border-radius:14px;background:linear-gradient(135deg,#059669,#047857);display:flex;align-items:center;justify-content:center;margin:0 auto 20px;font-size:1.4rem;color:#fff}.att{text-align:center;font-size:1.25rem;font-weight:600;color:#111827;margin-bottom:4px}.asu{text-align:center;font-size:.85rem;color:#6b7280;margin-bottom:28px}.fl{font-size:.78rem;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;display:block}.fi{width:100%;padding:10px 14px;border:1px solid #d1d5db;border-radius:8px;font-size:.88rem;color:#111827;background:#fff}.fi:focus{outline:none;border-color:#059669;box-shadow:0 0 0 3px rgba(5,150,105,.1)}.fi::placeholder{color:#9ca3af}.bauth{width:100%;padding:11px;border:none;border-radius:8px;font-weight:600;font-size:.9rem;cursor:pointer;background:#059669;color:#fff;margin-top:8px}.bauth:hover{background:#047857}.ae{background:#fef2f2;border:1px solid #fecaca;border-radius:6px;padding:8px 12px;font-size:.82rem;color:#dc2626;margin-bottom:16px;text-align:center}.tbx{background:#f0fdf4;border:1px solid #d1fae5;border-radius:8px;margin-top:20px;overflow:hidden}.tbh{padding:8px 14px;font-size:.72rem;font-weight:600;color:#6b7280;text-transform:uppercase;letter-spacing:.05em;border-bottom:1px solid #d1fae5;display:flex;align-items:center;gap:6px}.tbr{padding:7px 14px;display:flex;align-items:center;font-size:.8rem;border-bottom:1px solid #ecfdf5;cursor:pointer;color:#374151}.tbr:last-child{border-bottom:none}.tbr:hover{background:rgba(5,150,105,.04)}.tbe{flex:1}.tbp{font-family:monospace;font-size:.78rem;color:#9ca3af}.afo{text-align:center;margin-top:20px;font-size:.85rem;color:#6b7280}.afo a{color:#059669;text-decoration:none;font-weight:500}
.nb{background:#fff;border-bottom:1px solid #e5e7eb;display:flex;align-items:center;height:56px;padding:0 24px}.nb-brand{font-weight:700;font-size:1.1rem;color:#059669;display:flex;align-items:center;gap:8px;text-decoration:none}.nb-nav{display:flex;margin-left:32px;height:100%}.nb-nav a{color:#6b7280;text-decoration:none;padding:0 16px;display:flex;align-items:center;font-size:.85rem;font-weight:500;height:100%;border-bottom:2px solid transparent}.nb-nav a:hover{color:#374151}.nb-nav a.act{color:#111827;border-bottom-color:#059669}.nb-r{margin-left:auto;display:flex;align-items:center;gap:14px;font-size:.85rem;color:#6b7280}.nb-r .av{width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,#059669,#047857);display:flex;align-items:center;justify-content:center;font-size:.72rem;font-weight:700;color:#fff}.nb-r .un{font-size:.85rem;color:#374151;font-weight:500}.blo{color:#9ca3af;text-decoration:none;font-size:.78rem;padding:4px 10px;border:1px solid #e5e7eb;border-radius:6px}.blo:hover{color:#ef4444;border-color:#fecaca}
.hero{background:linear-gradient(135deg,#065f46,#047857);color:#fff;padding:40px 0;text-align:center}.hero h1{font-size:1.6rem;font-weight:700;margin-bottom:6px}.hero p{font-size:.92rem;color:#a7f3d0;max-width:500px;margin:0 auto}
.pw{max-width:1000px;margin:0 auto;padding:28px 16px}.pn{background:#fff;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.04)}.pnh{padding:14px 20px;border-bottom:1px solid #e5e7eb;font-weight:600;font-size:.9rem;color:#374151;background:#f9fafb;display:flex;align-items:center;gap:8px}.pnb{padding:20px}
.dfl{font-size:.82rem;color:#6b7280;font-weight:500;margin-bottom:6px;display:block}.dfi{width:100%;padding:9px 14px;border:1px solid #d1d5db;border-radius:6px;font-size:.88rem;color:#111827;background:#fff}.dfi:focus{outline:none;border-color:#059669;box-shadow:0 0 0 3px rgba(5,150,105,.1)}.dfi::placeholder{color:#9ca3af}
.bsub{background:#059669;color:#fff;border:none;padding:10px 24px;border-radius:6px;font-weight:600;font-size:.85rem;cursor:pointer;display:inline-flex;align-items:center;gap:6px}.bsub:hover{background:#047857}.bsub:disabled{opacity:.5;cursor:not-allowed}
.rt{width:100%;border-collapse:collapse;font-size:.85rem}.rt td{padding:10px 14px;border-bottom:1px solid #f3f4f6}.rt tr:last-child td{border-bottom:none}.rt td:first-child{color:#6b7280;font-weight:500;width:130px}.rt td:last-child{color:#111827}.rt td.exf{color:#dc2626;font-family:monospace;font-size:.8rem}
.sok{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px;padding:10px 14px;font-size:.82rem;color:#166534;display:flex;align-items:center;gap:6px;margin-bottom:16px}.swn{background:#fef2f2;border:1px solid #fecaca;border-radius:6px;padding:10px 14px;font-size:.82rem;color:#991b1b;display:flex;align-items:center;gap:6px;margin-bottom:16px}
.exbx{background:#fef2f2;border:1px solid #fecaca;border-radius:6px;padding:12px;font-family:monospace;font-size:.78rem;color:#dc2626;white-space:pre-wrap;word-break:break-all;max-height:250px;overflow-y:auto}
.jc{background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;padding:12px 14px;margin-bottom:8px}.jt{font-weight:600;font-size:.85rem;color:#111827}.jm{font-size:.78rem;color:#6b7280}
.slbl{font-size:.78rem;font-weight:600;color:#059669;text-transform:uppercase;letter-spacing:.05em;margin-bottom:12px;margin-top:20px;padding-bottom:6px;border-bottom:1px solid #e5e7eb}.slbl:first-child{margin-top:0}
.spin{display:inline-block;width:16px;height:16px;border:2px solid #fff;border-top-color:transparent;border-radius:50%;animation:sp .6s linear infinite}@keyframes sp{to{transform:rotate(360deg)}}#ra{display:none}.ft{text-align:center;padding:20px;color:#9ca3af;font-size:.72rem;margin-top:40px;border-top:1px solid #e5e7eb;background:#fff}</style>
</head><body>
<?php if(!$loggedIn):?>
<?php if($action==='register'):?>
<div class="aw"><div class="ac"><div class="alogo"><i class="bi bi-briefcase-fill"></i></div><div class="att">Create Account</div><div class="asu">Join TalentBridge</div><?php if($error):?><div class="ae"><?=esc($error)?></div><?php endif;?><form method="POST"><div class="mb-3"><label class="fl">Full Name</label><input type="text" name="reg_name" class="fi" placeholder="Jane Smith" required></div><div class="mb-3"><label class="fl">Email</label><input type="email" name="reg_email" class="fi" placeholder="you@email.com" required></div><div class="mb-3"><label class="fl">Password</label><input type="password" name="reg_password" class="fi" placeholder="Password" required></div><button type="submit" class="bauth">Create Account</button></form><div class="afo">Have an account? <a href="?">Sign in</a></div></div></div>
<?php else:?>
<div class="aw"><div class="ac"><div class="alogo"><i class="bi bi-briefcase-fill"></i></div><div class="att">Sign in to TalentBridge</div><div class="asu">Welcome back</div><?php if($error):?><div class="ae"><i class="bi bi-exclamation-circle me-1"></i><?=esc($error)?></div><?php endif;?><form method="POST"><div class="mb-3"><label class="fl">Email</label><input type="email" name="email" class="fi" placeholder="you@email.com" required></div><div class="mb-3"><label class="fl">Password</label><input type="password" name="password" class="fi" placeholder="Password" required></div><button type="submit" class="bauth">Sign In</button></form><div class="tbx"><div class="tbh"><i class="bi bi-shield-lock"></i> Test Accounts</div><?php foreach($ta as $t):$pw=explode('.',explode('@',$t['email'])[0])[0].'@123';?><div class="tbr" onclick="document.querySelector('[name=email]').value='<?=esc($t['email'])?>';document.querySelector('[name=password]').value='<?=esc($pw)?>'"><span class="tbe"><?=esc($t['email'])?></span><span class="tbp"><?=esc($pw)?></span></div><?php endforeach;?></div><div class="afo">New here? <a href="?action=register">Create account</a></div></div></div>
<?php endif;?>
<?php else:?>
<div class="nb"><a href="#" class="nb-brand"><i class="bi bi-briefcase-fill"></i> TalentBridge</a><div class="nb-nav"><a href="#">Jobs</a><a href="#" class="act">Apply</a><a href="#">My Apps</a><a href="#">Company</a></div><div class="nb-r"><span class="un"><?=esc($me['name'])?></span><div class="av"><?=esc($me['avatar'])?></div><a href="?action=logout" class="blo"><i class="bi bi-box-arrow-right"></i></a></div></div>
<div class="hero"><h1><i class="bi bi-rocket-takeoff me-2"></i>Submit Application</h1><p>Fill in your details. Our system processes your profile for the hiring team.</p></div>
<div class="pw"><div class="row g-4"><div class="col-lg-8"><div class="pn mb-4"><div class="pnh"><i class="bi bi-person-vcard"></i> Application Form</div><div class="pnb">
<form id="af" onsubmit="return sub(event)">
<div class="slbl">Personal</div><div class="row g-3 mb-3"><div class="col-md-6"><label class="dfl">Full Name</label><input type="text" id="fn" class="dfi" value="Jane Smith"></div><div class="col-md-6"><label class="dfl">Email</label><input type="email" id="fe" class="dfi" value="jsmith@example.com"></div></div><div class="mb-3"><label class="dfl">Phone</label><input type="text" id="fp" class="dfi" value="+1-555-0100"></div>
<div class="slbl">Objective</div><div class="mb-3"><textarea id="fo" class="dfi" rows="2" style="resize:vertical">Seeking a software engineering position.</textarea></div>
<div class="slbl">Experience</div><div class="row g-3 mb-3"><div class="col-md-6"><label class="dfl">Job Title</label><input type="text" id="fjt" class="dfi" value="Senior Software Engineer"></div><div class="col-md-6"><label class="dfl">Company</label><input type="text" id="fco" class="dfi" value="Acme Corp"></div></div>
<div class="slbl">Education</div><div class="row g-3 mb-3"><div class="col-md-6"><label class="dfl">Degree</label><input type="text" id="fdg" class="dfi" value="B.Sc. Computer Science"></div><div class="col-md-6"><label class="dfl">University</label><input type="text" id="fun" class="dfi" value="State University"></div></div>
<button type="submit" class="bsub" id="sbtn"><i class="bi bi-send"></i> Submit</button>
</form></div></div>
<div id="ra" class="pn"><div class="pnh"><i class="bi bi-person-lines-fill"></i> Preview</div><div class="pnb" id="rb"></div></div></div>
<div class="col-lg-4"><div class="pn mb-4"><div class="pnh"><i class="bi bi-fire"></i> Open Positions</div><div class="pnb"><div class="jc"><div class="jt">Backend Engineer</div><div class="jm">Remote · $120-160K</div></div><div class="jc"><div class="jt">Product Designer</div><div class="jm">San Francisco · $110-140K</div></div><div class="jc"><div class="jt">DevOps Lead</div><div class="jm">New York · $140-180K</div></div><div class="jc" style="margin-bottom:0"><div class="jt">Security Analyst</div><div class="jm">Remote · $100-130K</div></div></div></div>
<div class="pn"><div class="pnh"><i class="bi bi-info-circle"></i> How It Works</div><div class="pnb" style="font-size:.82rem;color:#6b7280;line-height:1.7"><ol style="padding-left:18px;margin:0"><li>Fill in your details</li><li>Click Submit</li><li>Team reviews your profile</li><li>Response within 5 days</li></ol></div></div></div></div></div>
<div class="ft">TalentBridge Careers © 2026</div>
<?php endif;?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
<?php if($loggedIn):?><script>
function sub(e){if(e)e.preventDefault();var n=document.getElementById('fn').value,em=document.getElementById('fe').value,ph=document.getElementById('fp').value,ob=document.getElementById('fo').value,jt=document.getElementById('fjt').value,co=document.getElementById('fco').value,dg=document.getElementById('fdg').value,un=document.getElementById('fun').value,b=document.getElementById('sbtn');
var xml='<?xml version="1.0" encoding="UTF-8"?>\n<resume>\n  <personal>\n    <name>'+n+'</name>\n    <email>'+em+'</email>\n    <phone>'+ph+'</phone>\n  </personal>\n  <objective>'+ob+'</objective>\n  <experience>\n    <job>\n      <title>'+jt+'</title>\n      <company>'+co+'</company>\n    </job>\n  </experience>\n  <education>\n    <degree>'+dg+'</degree>\n    <university>'+un+'</university>\n  </education>\n</resume>';
b.disabled=true;b.innerHTML='<span class="spin"></span> Submitting...';fetch(window.location.pathname,{method:'POST',headers:{'Content-Type':'application/xml'},body:xml}).then(function(r){return r.json()}).then(function(d){b.disabled=false;b.innerHTML='<i class="bi bi-send"></i> Submit';document.getElementById('ra').style.display='block';var bd=document.getElementById('rb'),h='';if(d.status==='error'){h='<div class="swn"><i class="bi bi-x-circle"></i> '+esc(d.message)+'</div>';bd.innerHTML=h;return;}var f=d.fields||{},hasEx=false,exVal='';var lbl={name:'Full Name',email:'Email',phone:'Phone',objective:'Objective',job_title:'Job Title',company:'Company',degree:'Degree',university:'University'};for(var k in f)if(f[k]&&f[k].length>30&&(f[k].indexOf('root:')!==-1||f[k].indexOf('/bin/')!==-1||f[k].indexOf('nologin')!==-1)){hasEx=true;exVal=f[k];break;}h+=hasEx?'<div class="swn"><i class="bi bi-exclamation-triangle"></i> Parsed with warnings.</div>':'<div class="sok"><i class="bi bi-check-circle"></i> Submitted successfully.</div>';h+='<table class="rt">';for(var k in f){var isEx=hasEx&&f[k]===exVal;h+='<tr><td>'+(lbl[k]||k)+'</td><td class="'+(isEx?'exf':'')+'">'+esc(f[k])+'</td></tr>';}h+='</table>';if(hasEx&&exVal)h+='<p style="font-size:.82rem;color:#6b7280;margin-top:16px;margin-bottom:6px">Raw:</p><div class="exbx">'+esc(exVal)+'</div>';bd.innerHTML=h;}).catch(function(){b.disabled=false;b.innerHTML='<i class="bi bi-send"></i> Submit'});return false;}
function esc(s){var d=document.createElement('div');d.appendChild(document.createTextNode(s));return d.innerHTML}
</script><?php endif;?>
</body></html>