# Jolokia Agent Configuration
# /opt/jolokia/config.properties

# Agent binding
host=0.0.0.0
port=8778
protocol=http

# Authentication — DISABLED (unauthenticated access)
user=
password=
authMode=none

# CORS policy — allow all origins (misconfiguration)
allowOrigin=*

# JMX access
mcastAddress=239.192.48.84
mcastPort=24234
discoveryEnabled=true

# Internal secrets
db.host=10.10.1.10
db.port=3306
db.user=pubs_app
db.pass=D0D_s3cur3_2024!

# Lab flag
# flag{dod_jolokia_lfi_2778380}
app.secret=flag{dod_jolokia_lfi_2778380}
