; DoD Personnel Records System — Application Configuration
; C:\ProgramData\dod_app\config.ini
; Classification: UNCLASSIFIED // FOR OFFICIAL USE ONLY

[application]
name        = DoD Personnel Records System
version     = 3.4.1
build       = 20190115
env         = production
base_url    = https://████.mil/
gwt_module  = gwtmain

[database]
host        = 10.10.1.10
port        = 1433
name        = DoDPersonnelDB
user        = dod_app_user
password    = D0D_App_S3rv1c3_2019!
pool_size   = 10

[security]
; Lab flag
; flag{dod_gwt_lfi_497771}
app_secret  = flag{dod_gwt_lfi_497771}
admin_hash  = $2y$12$xK9mQpR3nL7vT2wY8uB6XeOjF5hN1dA4cZ3sE0gI7kM9pW6yV1oU
session_timeout = 1800
csrf_enabled = false

[ldap]
server      = 10.10.1.20
port        = 389
base_dn     = DC=dod,DC=mil
bind_dn     = CN=svc-gwt,OU=ServiceAccounts,DC=dod,DC=mil
bind_pass   = Ldap_Svc_2019#

[logging]
path        = C:\inetpub\logs\LogFiles\W3SVC1\
level       = INFO
audit       = true
